name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or the branch you want to trigger the workflow from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Create gh-pages branch directory
      run: |
        mkdir gh-pages
        cp -r elements/test1.html gh-pages/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gh-pages